### ISSUE TITLE
Combine custom tags with no HTML escaping

### ISSUE THREAD

**Issue by davidanthoff** [jverzani/Mustache.jl#114]
How can I combine custom tags with the option to not do the HTML escaping?

In particular, I have a call like this:
```
Mustache.render(file, content, vals, tags = ("\$[[", "]]"))
```
I would have thought that `$[[{JL_VERSION_MATRIX}]]` would work (i.e. use the custom tag to demark a substitution, and then one pair of curly braces to prevent the HTML escaping), but that doesn't seem to be the case.

**Comment by jverzani** [comment]
Thanks! This should  work as you expected.  I think #116 will address this.  Please let me know  if  you bump  into other issues.

**Comment by davidanthoff** [comment]
Awesome, thanks!

I can't really test this with a version that isn't tagged, though (the whole thing is part of a complicated automated github action setup). Could you maybe tag a new release?

**Comment by jverzani** [comment]
Should be tagged now.

**Comment by davidanthoff** [comment]
Works perfectly now, thanks a lot for the quick turnaround!
