### ISSUE TITLE
"/" produces "&#x2F"

### ISSUE THREAD

**Issue by SimonDanisch** [jverzani/Mustache.jl#14]
Hi,
I get some weird tokens in my render results.
Minimal code to reproduce:

``` Julia
 a = mt"{{test}}"
view = ["test"=>"/"]

julia> render(a,view)
"&#x2F;"
```

I'm on Ubuntu with Julia 0.3.0, if that matters ;)
Thanks for the awesome package by the way!

Best,
Simon

**Comment by amellnik** [comment]
I ran into a similar thing trying to write values with strings containing single ticks like "character literals look like 'c'".  This might be worth adding to the documentation as right now the only mention of {{{ }}} is for symbols.  Cheers!

**Comment by jverzani** [comment]
I'm not quite sure what you are expecting, can you clarify? I'm happy to add to the docs if they make things more clear. I did this test: `render("character literals look like '{{{:x}}}'", x='c')` with double and triple braces and got the same output (as though 'c' were just the string "c").

**Comment by amellnik** [comment]
I thought it might be worth mentioning in the docs that the user needs to use triple braces in order for replacements containing things like ' and \ to work.  Sample code might look like

    using Mustache
    d = Dict()
    d["sq"] = "'woah'"
    tpl1 = mt"""
    Here comes some single quotes {{{sq}}}
    """
    tpl2 = mt"""
    Here comes some single quotes {{sq}}
    """
    print(render(tpl1,d))
    print(render(tpl2,d))

I was about to file an issue before I saw this thread and tried it with triple brackets.

**Comment by jverzani** [comment]
Thanks! I just pushed some info on what gets escaped to the README page.

On Wed, Jul 1, 2015 at 7:27 PM, Alex Mellnik <notifications@github.com>
wrote:

> I thought it might be worth mentioning in the docs that the user needs to
> use triple braces in order for replacements containing things like ' and \
> to work. Sample code might look like
>
> using Mustache
> d = Dict()
> d["sq"] = "'woah'"
> tpl1 = mt"""
> Here comes some single quotes {{{sq}}}
> """
> tpl2 = mt"""
> Here comes some single quotes {{sq}}
> """
> print(render(tpl1,d))
> print(render(tpl2,d))
>
> I was about to file an issue before I saw this thread and tried it with
> triple brackets.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jverzani/Mustache.jl/issues/14#issuecomment-117849107>
> .
>



-- 
John Verzani
Chair, Department of Mathematics
College of Staten Island, CUNY
verzani@math.csi.cuny.edu
