### ISSUE TITLE
Mysterious warning when using Mustache in 0.3.10 or 0.3.11

### ISSUE THREAD

**Issue by amellnik** [jverzani/Mustache.jl#21]
```
julia> using Mustache
symbol could not be found jl_generating_output (-1): The specified procedure could not be found.
```
This is on 64 bit Windows 8.1 with Mustache 0.0.12.  Running the same again doesn't generate the warning, and Mustache appears to be working fine.

**Comment by jverzani** [comment]
Boy, that is mysterious. I can't replicate it in my Windows 8 VM. Sorry, I have no idea where this comes from. If you have some thoughts, please reopen and let me know.
