### ISSUE TITLE
Rendering partials

### ISSUE THREAD

**Issue by essenciary** [jverzani/Mustache.jl#25]
Is there any option for rendering partials (mustache views inside a main mustache template)?

**Comment by jverzani** [comment]
This works, though I haven't tested it extensively:

test.tpl:
```
This is mustache

{{> p1.tpl }} what is this?

{{y}}
```

p1.tpl:
```
x is: {{x}}.
```
and then

```
print(Mustache.render_from_file("test.tpl", Dict("x"=>"XXX", "y" => "YYY")))
```

Is that what you wanted or something else?

**Comment by essenciary** [comment]
Thanks for your reply - looks like what I wanted but I need to try it out to be sure. Be right back.

**Comment by essenciary** [comment]
The example above works great, thanks! 
However, it chokes when passing a path rather than just the partial's file name. Any advice on how to achieve that please?

**Comment by jverzani** [comment]
The parsed string, `filepath`, gets passed to `template_from_file` which in turn leads to a call of `f = open(filepath)`. So you need to pass in something that can be passed to `open`. I checked that a full path name works on my mac. I'm not sure about Windows, but would guess you need something akin to C:\\path1\\path2\\template_file .

**Comment by essenciary** [comment]
Thanks - indeed, it does work. I think I had a bug in creating the path the first time I tried. Seems to work equally well with relative paths too (I'm on a Mac as well). 

Many thanks, much appreciated!
