### ISSUE TITLE
Julia 0.5 and Requires

### ISSUE THREAD

**Issue by SimonDanisch** [jverzani/Mustache.jl#26]
Can we try to remove `Requires`? It's not working on `0.5` and it seems like this could be done differently ;) I can supply a PR if you want! Just wanted to discuss in what direction it should go...

**Comment by jverzani** [comment]
Sure. Is your idea just to require DataFrames? That's what I would do at first thought. Now that pre-compilation makes it not so tedious to load, this seems doable. If you have something more elegant, please share.

**Comment by jverzani** [comment]
I just pushed in a change to address this (4e2ccfc). Rather than load DataFrames, i test for it using a heuristic where appropriate. This cuts down the load time in half, but may have other issues. If you see something funny, please let me know.

**Comment by SimonDanisch** [comment]
Neat fix! :D thanks!

**Comment by SimonDanisch** [comment]
Any reason why we can't have this tagged?

**Comment by jverzani** [comment]
Sorry. Will do so in the next few days.

On Tuesday, May 17, 2016, Simon <notifications@github.com> wrote:

> Any reason why we can't have this tagged?
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/jverzani/Mustache.jl/issues/26#issuecomment-219771123>
>


-- 
John Verzani
Chair, Department of Mathematics
College of Staten Island, CUNY
verzani@math.csi.cuny.edu

**Comment by jverzani** [comment]
Okay, all done now. Thanks for the reminder.

On Tue, May 17, 2016 at 1:03 PM, John Verzani <jverzani@gmail.com> wrote:

> Sorry. Will do so in the next few days.
>
>
> On Tuesday, May 17, 2016, Simon <notifications@github.com> wrote:
>
>> Any reason why we can't have this tagged?
>>
>> —
>> You are receiving this because you modified the open/close state.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/jverzani/Mustache.jl/issues/26#issuecomment-219771123>
>>
>
>
> --
> John Verzani
> Chair, Department of Mathematics
> College of Staten Island, CUNY
> verzani@math.csi.cuny.edu
>



-- 
John Verzani
Chair, Department of Mathematics
College of Staten Island, CUNY
verzani@math.csi.cuny.edu
