### ISSUE TITLE
Access nested properties

### ISSUE THREAD

**Issue by essenciary** [jverzani/Mustache.jl#31]
Is it possible in any way to access nested properties? (I've seen the error when attempting it, so obviously can't be done directly). 

Say I have a `type` `Thing` that has a `location` property. Which is an instance of a `Location` `type`. 
```julia
type Location
  lat::Float64
  lon::Float64
end
```
```julia
type Thing
  location::Location
  name::AbstractString
end
```

And an array `things` as `Array{Thing,1}`. 

In the template I'd like to iterate over the `things` array and output `thing.name` and `thing.location.lat`. Can it be done?

**Comment by jverzani** [comment]
Thanks for the question! I think this recent addition does what you want. Here was my test case:

```

using Mustache

tpl = """
{{#:x}}
{{#.}}
{{#location}}
{{lat}}--{{lon}}
{{/location}}
{{name}}
{{/.}}
{{/:x}}
"""

x = [Thing(Location(1.,2.), "name"), Thing(Location(3.,4.), "nombre")]

print(Mustache.render(tpl, x=x))
```

If it works, let me know and I'll push to METADATA.

**Comment by essenciary** [comment]
Wow, this looks great, thanks! 

Let me give it a try, I need to add a test branch as I already went on and flattened the nested objects fields into a dict.

**Comment by essenciary** [comment]
@jverzani I tried your test but it doesn't seem to work for me. I've run a Pkg.update() - do I need to do anything else in order to get the latest updates? 

```julia
julia> print(Mustache.render(tpl, x=x))



--

name




--

nombre
```

**Comment by jverzani** [comment]
To test out this code you need to run `Pkg.checkout("Mustache", "master")`. (`update` is for new tagged versions.) If that works, you can run `Pkg.free("Mustache")` to get back on the officially released version. If the master version does what you are expecting, let me know and I tag a new version so that `Pkg.update` will pick it up. If not, let me know and I'll try to fix things.
