### ISSUE TITLE
Use Nullable and not Union(Void, T)

### ISSUE THREAD

**Issue by jverzani** [jverzani/Mustache.jl#40]
Look into this change mentioned in #38  to see if there are performance gains to be had.

**Comment by Kissaki** [comment]
The Julia 1.0 docs do not talk about a `Nullable` type, but mentions `Union{T, Nothing}` as a Julia type for what is nullable types in other languages.

What is this issue about?

**Comment by jverzani** [comment]
This is an old issue as no longer relevant.
