### ISSUE TITLE
Switching delimiters in the template

### ISSUE THREAD

**Issue by c42f** [jverzani/Mustache.jl#46]
According to the mustache spec (https://github.com/mustache/spec/blob/83b0721610a4e11832e83df19c73ace3289972b9/specs/delimiters.yml#L12), it should be possible to change delimiters inside the template, but this doesn't seem to work currently:

```julia
julia> Mustache.render(mt"""{{=<% %>=}} <% asdf %> <%={{ }}=%>""", Dict("asdf"=>"a"))
" <% asdf %> <%==%>"
```

**Comment by jverzani** [comment]
I punted on that implementation. I'll leave this open for incentive for it to be added.

**Comment by c42f** [comment]
Sure, no problem.

By the way, I found this while trying to template some LaTeX for Weave.jl, as latex uses braces extensively.
