### ISSUE TITLE
Section tags should not insert extra newlines

### ISSUE THREAD

**Issue by christopher-dG** [jverzani/Mustache.jl#47]
## Problem 

```
julia> println(s)
A
{{#:B}}
B
{{/:B}}
C

# Expected:
A
C

julia> println(render(s; B=false))
A

C

# Expected:
A
B
C

julia> println(render(s; B=true))
A

B

C
```

According to the [Mustache spec](https://github.com/mustache/spec/blob/master/specs/sections.yml#L211), a section tag on its own line should be removed entirely rather than replaced by an empty line. 

Note that I'm using regular strings, but the behaviour is the same  when replicated with the Mustache macro.

## Workaround

We can deal with this fairly easily, it just looks ugly.

```julia
julia> println(s)
A{{#:B}}
B{{/:B}}
C

julia> println(render(s; B=false))
A
C

julia> println(render(s; B=true))
A
B
C
```

```julia
julia> VERSION
v"0.6.0"
```

**Comment by jverzani** [comment]
Sorry, I tried to get this working, but couldn't see a direct solution given the parsing algorithm. Hopefully someone else will.
