### ISSUE TITLE
Release for Julia 1.0

### ISSUE THREAD

**Issue by Nosferican** [jverzani/Mustache.jl#59]
Leaving issue to track progress.

**Comment by jverzani** [comment]
If this goes through, then 1.0 should be supported:
https://github.com/JuliaLang/METADATA.jl/pull/16846

**Comment by Kissaki** [comment]
I am using Mustache with Julia 1.0. It seems to work fine!? What does this issue contain then?

**Comment by jverzani** [comment]
Should be good now.
