### ISSUE TITLE
Templates with CRLF line endings do not remove empty/section tag lines

### ISSUE THREAD

**Issue by Kissaki** [jverzani/Mustache.jl#75]
Given a template

```
{{#a}}
{{x}}
{{/a}}
```
the resulting rendered text should be only the middle line. The section tag lines that are otherwise whitespace/empty should be removed.

This works fine for templates with LF (`\n`) newlines. However, for CRLF templates this does not work.

**Comment by jverzani** [comment]
Hmm, I wasn't sure this was being handled properly, but the spec test was passing. Thanks for the attention.
