### ISSUE TITLE
Non existant partial inclusions fail silently

### ISSUE THREAD

**Issue by Kissaki** [jverzani/Mustache.jl#83]
When including partial files for parsing (`{{> filename }}`) from `Mustache.render_from_file` and the file is not found, no issue or error is returned. Instead, the the lib returns a parsed template as if nothing went wrong.

I would expect and error to be raised/`nothing` to be returned to indicate an error.

**Comment by jverzani** [comment]
Actually, in testing to try and fix #82, I see this test:  "The empty string should be used when the named partial is not found", so the current behavior seems to be the expected behavior.
