### ISSUE TITLE
Use of Tables.rowaccess

### ISSUE THREAD

**Issue by quinnj** [jverzani/Mustache.jl#96]
Just a note as I was perusing the use of Tables.jl in this package: [here](https://github.com/jverzani/Mustache.jl/blob/be192b51464db2da6390f2badba6dbf828d436bd/src/utils.jl#L47), [here](https://github.com/jverzani/Mustache.jl/blob/5c1212faa694c5aa2ad2435ec282350ec94fefdf/src/tokens.jl#L438), and [here](https://github.com/jverzani/Mustache.jl/blob/be192b51464db2da6390f2badba6dbf828d436bd/src/context.jl#L89), you could remove the call to `Tables.rowaccess` and just call `Tables.rows` directly. This works because Tables.jl itself provides a default fallback for `Tables.rows` in case the input table source is `Tables.rowaccess(x) == false`. Basically, you can always call `Tables.rows`, regardless of whether the input source is columnar or row-major.

**Comment by jverzani** [comment]
Nice. Thanks so much for letting me know!
